# Generated by Django 4.2.1 on 2023-05-25 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='articulo',
            name='articulo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='autor_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.autor'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='medio_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.medio'),
        ),
    ]
