# Generated by Django 4.2.1 on 2023-05-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_articulo_descripcion_articulo_articulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='articulo',
            field=models.URLField(null=True),
        ),
    ]
